// See the Electron documentation for details on how to use preload scripts:
// https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts
import { contextBridge, ipcRenderer } from 'electron';

import {
  CREATE_GATE,
  CREATE_DECK,
  CREATE_STRUCTURE_DECK,
  DELETE_DECK,
  DELETE_GATE,
  DELETE_STRUCTURE_DECK,
  LOAD_SETTINGS,
  OPEN_DIRECTORY,
  OPEN_FILE,
  OPEN_LOG_FILE,
  OPEN_SETTINGS_FILE,
  READ_GATE,
  READ_GATES,
  READ_DECK,
  READ_DECKS,
  READ_STRUCTURE_DECK,
  READ_STRUCTURE_DECKS,
  SAVE_SETTINGS,
  SHOW_MESSAGE_BOX,
  UPDATE_DECK,
  UPDATE_GATE,
  UPDATE_STRUCTURE_DECK,
  CAMPAIGN_DEPLOY,
  CAMPAIGN_VALIDATE,
  CONTENT_COMPILE,
  CONTENT_DEPLOY,
  CONTENT_DIFF,
  CONTENT_INSPECT,
  CONTENT_RESOLVE,
  CONTENT_REVEAL_SOURCE,
  CONTENT_DOCUMENT_LIST,
  CONTENT_DOCUMENT_READ,
  CONTENT_DOCUMENT_MUTATE,
  CONTENT_DECK_PREVIEW,
  CONTENT_DECK_WORKSPACE_READ,
  CONTENT_DECK_FOLDERS_BOOTSTRAP,
  CONTENT_SHOP_READ,
  CONTENT_SHOP_MUTATE,
  CONTENT_STRUCTURE_MUTATE,
  CONTENT_REGULATION_READ,
  CONTENT_REGULATION_MUTATE,
  CONTENT_LOCALIZATION_ASSET_INSPECT,
  CONTENT_LOCALIZATION_ASSET_MUTATE,
  CONTENT_RUNTIME_POLICY_READ,
  CONTENT_RUNTIME_POLICY_WRITE,
  CONTENT_VALIDATE,
  CATALOG_REFRESH,
  CATALOG_SEARCH,
  CATALOG_STATUS,
  CATALOG_CUSTOM_VALIDATE,
  CATALOG_SERVICE_GET,
  CATALOG_SERVICE_QUERY,
  CONFIG_SET_GAME_ROOT,
  CONFIG_SET_SOURCE_ROOT,
  CONFIG_SET_WORKSPACE_ROOT,
  CAMPAIGN_WORKSPACE_STATUS,
  CONFIG_SHOW,
  CORE_INFO,
  DEPLOYMENT_INSPECT,
  DEPLOYMENT_LAUNCH,
  DEPLOYMENT_LIST,
  RUNTIME_FETCH,
  RUNTIME_STATUS,
  WORKSPACE_INIT,
  WORKSPACE_INSPECT,
} from '../common/channel';
import {
  CreateGateRequest,
  CreateStructureDeckRequest,
  DeckPathRequest,
  DeckWriteRequest,
  DeleteGateRequest,
  DeleteStructureDeckRequest,
  ReadGateRequest,
  ReadGatesRequest,
  ReadStructureDeckRequest,
  ReadStructureDecksRequest,
  Settings,
  ShowMessageBoxRequest,
  UpdateGateRequest,
  UpdateStructureDeckRequest,
  CoreOperationResult,
  CorePathRequest,
  CorePathsRequest,
  CatalogRefreshRequest,
  CatalogSearchRequest,
  CatalogServiceGetRequest,
  CatalogServiceQueryRequest,
  CatalogServiceQueryResult,
  ContentCompileRequest,
  ContentDeployRequest,
  ContentOperationRequest,
  ContentRevealSourceRequest,
  ContentDocumentRequest,
  ContentDocumentMutationRequest,
  ContentDeckPreviewRequest,
  ContentDeckWorkspaceRequest,
  ContentDeckFoldersBootstrapRequest,
  ContentShopReadRequest,
  ContentShopMutationRequest,
  ContentStructureMutationRequest,
  ContentRegulationReadRequest,
  ContentRegulationMutationRequest,
  ContentLocalizationAssetMutationRequest,
  ContentRuntimePolicyRequest,
  ContentRuntimePolicyWriteRequest,
} from '../common/type';

// prettier-ignore
contextBridge.exposeInMainWorld('electron', {
  openDirectory: (path?: string) => ipcRenderer.invoke(OPEN_DIRECTORY, path),
  openFile: (path?: string) => ipcRenderer.invoke(OPEN_FILE, path),
  showMessageBox: (request: ShowMessageBoxRequest) => ipcRenderer.invoke(SHOW_MESSAGE_BOX, request),
  saveSettings: (settings: Settings) => ipcRenderer.invoke(SAVE_SETTINGS, settings),
  loadSettings: () => ipcRenderer.invoke(LOAD_SETTINGS),
  openSettingsFile: () => ipcRenderer.invoke(OPEN_SETTINGS_FILE),
  openLogFile: () => ipcRenderer.invoke(OPEN_LOG_FILE),
  readGates: (request: ReadGatesRequest) => ipcRenderer.invoke(READ_GATES, request),
  readGate: (request: ReadGateRequest) => ipcRenderer.invoke(READ_GATE, request),
  createGate: (request: CreateGateRequest) => ipcRenderer.invoke(CREATE_GATE, request),
  updateGate: (request: UpdateGateRequest) => ipcRenderer.invoke(UPDATE_GATE, request),
  deleteGate: (request: DeleteGateRequest) => ipcRenderer.invoke(DELETE_GATE, request),
  readStructureDecks: (request: ReadStructureDecksRequest) => ipcRenderer.invoke(READ_STRUCTURE_DECKS, request),
  readStructureDeck: (request: ReadStructureDeckRequest) => ipcRenderer.invoke(READ_STRUCTURE_DECK, request),
  createStructureDeck: (request: CreateStructureDeckRequest) => ipcRenderer.invoke(CREATE_STRUCTURE_DECK, request),
  updateStructureDeck: (request: UpdateStructureDeckRequest) => ipcRenderer.invoke(UPDATE_STRUCTURE_DECK, request),
  deleteStructureDeck: (request: DeleteStructureDeckRequest) => ipcRenderer.invoke(DELETE_STRUCTURE_DECK, request),
  readDecks: (): Promise<CoreOperationResult> => ipcRenderer.invoke(READ_DECKS),
  readDeck: (request: DeckPathRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(READ_DECK, request),
  createDeck: (request: DeckWriteRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CREATE_DECK, request),
  updateDeck: (request: DeckWriteRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(UPDATE_DECK, request),
  deleteDeck: (request: DeckPathRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(DELETE_DECK, request),
  coreInfo: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CORE_INFO),
  configShow: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CONFIG_SHOW),
  configSetGameRoot: (request: CorePathRequest) => ipcRenderer.invoke(CONFIG_SET_GAME_ROOT, request),
  configSetSourceRoot: (request: CorePathRequest) => ipcRenderer.invoke(CONFIG_SET_SOURCE_ROOT, request),
  configSetWorkspaceRoot: (request: CorePathRequest) => ipcRenderer.invoke(CONFIG_SET_WORKSPACE_ROOT, request),
  campaignWorkspaceStatus: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CAMPAIGN_WORKSPACE_STATUS),
  workspaceInit: (request?: CorePathsRequest) => ipcRenderer.invoke(WORKSPACE_INIT, request),
  workspaceInspect: (request?: CorePathsRequest) => ipcRenderer.invoke(WORKSPACE_INSPECT, request),
  campaignValidate: (request?: CorePathsRequest) => ipcRenderer.invoke(CAMPAIGN_VALIDATE, request),
  campaignDeploy: (request?: CorePathsRequest) => ipcRenderer.invoke(CAMPAIGN_DEPLOY, request),
  contentInspect: (request?: ContentOperationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_INSPECT, request),
  contentResolve: (request?: ContentOperationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_RESOLVE, request),
  contentValidate: (request?: ContentOperationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_VALIDATE, request),
  contentCompile: (request: ContentCompileRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_COMPILE, request),
  contentDiff: (request?: ContentOperationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DIFF, request),
  contentDeploy: (request?: ContentDeployRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DEPLOY, request),
  contentRevealSource: (request: ContentRevealSourceRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_REVEAL_SOURCE, request),
  contentDocumentList: (request?: ContentDocumentRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DOCUMENT_LIST, request),
  contentDocumentRead: (request: ContentDocumentRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DOCUMENT_READ, request),
  contentDocumentMutate: (request: ContentDocumentMutationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DOCUMENT_MUTATE, request),
  contentDeckPreview: (request: ContentDeckPreviewRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DECK_PREVIEW, request),
  contentDeckWorkspaceRead: (request?: ContentDeckWorkspaceRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DECK_WORKSPACE_READ, request),
  contentDeckFoldersBootstrap: (request: ContentDeckFoldersBootstrapRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_DECK_FOLDERS_BOOTSTRAP, request),
  contentShopRead: (request: ContentShopReadRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_SHOP_READ, request),
  contentShopMutate: (request: ContentShopMutationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_SHOP_MUTATE, request),
  contentStructureMutate: (request: ContentStructureMutationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_STRUCTURE_MUTATE, request),
  contentRegulationRead: (request: ContentRegulationReadRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_REGULATION_READ, request),
  contentRegulationMutate: (request: ContentRegulationMutationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_REGULATION_MUTATE, request),
  contentLocalizationAssetInspect: (request?: ContentOperationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_LOCALIZATION_ASSET_INSPECT, request),
  contentLocalizationAssetMutate: (request: ContentLocalizationAssetMutationRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_LOCALIZATION_ASSET_MUTATE, request),
  contentRuntimePolicyRead: (request?: ContentRuntimePolicyRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_RUNTIME_POLICY_READ, request),
  contentRuntimePolicyWrite: (request: ContentRuntimePolicyWriteRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CONTENT_RUNTIME_POLICY_WRITE, request),
  runtimeStatus: () => ipcRenderer.invoke(RUNTIME_STATUS),
  runtimeFetch: () => ipcRenderer.invoke(RUNTIME_FETCH),
  catalogStatus: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_STATUS),
  catalogRefresh: (request?: CatalogRefreshRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_REFRESH, request),
  catalogSearch: (request: CatalogSearchRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_SEARCH, request),
  catalogCustomValidate: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_CUSTOM_VALIDATE),
  catalogServiceGet: (request: CatalogServiceGetRequest): Promise<CoreOperationResult<CatalogServiceQueryResult>> => ipcRenderer.invoke(CATALOG_SERVICE_GET, request),
  catalogServiceQuery: (request: CatalogServiceQueryRequest): Promise<CoreOperationResult<CatalogServiceQueryResult>> => ipcRenderer.invoke(CATALOG_SERVICE_QUERY, request),
  deploymentList: (request?: CorePathsRequest) => ipcRenderer.invoke(DEPLOYMENT_LIST, request),
  deploymentInspect: (request: CorePathRequest) => ipcRenderer.invoke(DEPLOYMENT_INSPECT, request),
  deploymentLaunch: (request: CorePathRequest) => ipcRenderer.invoke(DEPLOYMENT_LAUNCH, request),
});
