// See the Electron documentation for details on how to use preload scripts:
// https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts
import { contextBridge, ipcRenderer } from 'electron';

import {
  CREATE_GATE,
  CREATE_DECK,
  CREATE_STRUCTURE_DECK,
  DELETE_DECK,
  DELETE_GATE,
  DELETE_STRUCTURE_DECK,
  LOAD_SETTINGS,
  OPEN_DIRECTORY,
  OPEN_FILE,
  OPEN_LOG_FILE,
  OPEN_SETTINGS_FILE,
  READ_GATE,
  READ_GATES,
  READ_DECK,
  READ_DECKS,
  READ_STRUCTURE_DECK,
  READ_STRUCTURE_DECKS,
  SAVE_SETTINGS,
  SHOW_MESSAGE_BOX,
  UPDATE_DECK,
  UPDATE_GATE,
  UPDATE_STRUCTURE_DECK,
  CAMPAIGN_DEPLOY,
  CAMPAIGN_VALIDATE,
  CATALOG_REFRESH,
  CATALOG_SEARCH,
  CATALOG_STATUS,
  CONFIG_SET_GAME_ROOT,
  CONFIG_SET_SOURCE_ROOT,
  CONFIG_SHOW,
  CORE_INFO,
  DEPLOYMENT_INSPECT,
  DEPLOYMENT_LAUNCH,
  DEPLOYMENT_LIST,
  RUNTIME_FETCH,
  RUNTIME_STATUS,
  WORKSPACE_INIT,
  WORKSPACE_INSPECT,
} from '../common/channel';
import {
  CreateGateRequest,
  CreateStructureDeckRequest,
  DeckPathRequest,
  DeckWriteRequest,
  DeleteGateRequest,
  DeleteStructureDeckRequest,
  ReadGateRequest,
  ReadGatesRequest,
  ReadStructureDeckRequest,
  ReadStructureDecksRequest,
  Settings,
  ShowMessageBoxRequest,
  UpdateGateRequest,
  UpdateStructureDeckRequest,
  CoreOperationResult,
  CorePathRequest,
  CorePathsRequest,
  CatalogRefreshRequest,
  CatalogSearchRequest,
} from '../common/type';

// prettier-ignore
contextBridge.exposeInMainWorld('electron', {
  openDirectory: (path?: string) => ipcRenderer.invoke(OPEN_DIRECTORY, path),
  openFile: (path?: string) => ipcRenderer.invoke(OPEN_FILE, path),
  showMessageBox: (request: ShowMessageBoxRequest) => ipcRenderer.invoke(SHOW_MESSAGE_BOX, request),
  saveSettings: (settings: Settings) => ipcRenderer.invoke(SAVE_SETTINGS, settings),
  loadSettings: () => ipcRenderer.invoke(LOAD_SETTINGS),
  openSettingsFile: () => ipcRenderer.invoke(OPEN_SETTINGS_FILE),
  openLogFile: () => ipcRenderer.invoke(OPEN_LOG_FILE),
  readGates: (request: ReadGatesRequest) => ipcRenderer.invoke(READ_GATES, request),
  readGate: (request: ReadGateRequest) => ipcRenderer.invoke(READ_GATE, request),
  createGate: (request: CreateGateRequest) => ipcRenderer.invoke(CREATE_GATE, request),
  updateGate: (request: UpdateGateRequest) => ipcRenderer.invoke(UPDATE_GATE, request),
  deleteGate: (request: DeleteGateRequest) => ipcRenderer.invoke(DELETE_GATE, request),
  readStructureDecks: (request: ReadStructureDecksRequest) => ipcRenderer.invoke(READ_STRUCTURE_DECKS, request),
  readStructureDeck: (request: ReadStructureDeckRequest) => ipcRenderer.invoke(READ_STRUCTURE_DECK, request),
  createStructureDeck: (request: CreateStructureDeckRequest) => ipcRenderer.invoke(CREATE_STRUCTURE_DECK, request),
  updateStructureDeck: (request: UpdateStructureDeckRequest) => ipcRenderer.invoke(UPDATE_STRUCTURE_DECK, request),
  deleteStructureDeck: (request: DeleteStructureDeckRequest) => ipcRenderer.invoke(DELETE_STRUCTURE_DECK, request),
  readDecks: (): Promise<CoreOperationResult> => ipcRenderer.invoke(READ_DECKS),
  readDeck: (request: DeckPathRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(READ_DECK, request),
  createDeck: (request: DeckWriteRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CREATE_DECK, request),
  updateDeck: (request: DeckWriteRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(UPDATE_DECK, request),
  deleteDeck: (request: DeckPathRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(DELETE_DECK, request),
  coreInfo: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CORE_INFO),
  configShow: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CONFIG_SHOW),
  configSetGameRoot: (request: CorePathRequest) => ipcRenderer.invoke(CONFIG_SET_GAME_ROOT, request),
  configSetSourceRoot: (request: CorePathRequest) => ipcRenderer.invoke(CONFIG_SET_SOURCE_ROOT, request),
  workspaceInit: (request?: CorePathsRequest) => ipcRenderer.invoke(WORKSPACE_INIT, request),
  workspaceInspect: (request?: CorePathsRequest) => ipcRenderer.invoke(WORKSPACE_INSPECT, request),
  campaignValidate: (request?: CorePathsRequest) => ipcRenderer.invoke(CAMPAIGN_VALIDATE, request),
  campaignDeploy: (request?: CorePathsRequest) => ipcRenderer.invoke(CAMPAIGN_DEPLOY, request),
  runtimeStatus: () => ipcRenderer.invoke(RUNTIME_STATUS),
  runtimeFetch: () => ipcRenderer.invoke(RUNTIME_FETCH),
  catalogStatus: (): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_STATUS),
  catalogRefresh: (request?: CatalogRefreshRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_REFRESH, request),
  catalogSearch: (request: CatalogSearchRequest): Promise<CoreOperationResult> => ipcRenderer.invoke(CATALOG_SEARCH, request),
  deploymentList: (request?: CorePathsRequest) => ipcRenderer.invoke(DEPLOYMENT_LIST, request),
  deploymentInspect: (request: CorePathRequest) => ipcRenderer.invoke(DEPLOYMENT_INSPECT, request),
  deploymentLaunch: (request: CorePathRequest) => ipcRenderer.invoke(DEPLOYMENT_LAUNCH, request),
});
