export const OPEN_DIRECTORY = 'OPEN_DIRECTORY';
export const OPEN_FILE = 'OPEN_FILE';
export const SHOW_MESSAGE_BOX = 'SHOW_MESSAGE_BOX';

export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const OPEN_LOG_FILE = 'OPEN_LOG_FILE';
export const OPEN_SETTINGS_FILE = 'OPEN_SETTINGS_FILE';

export const READ_GATES = 'READ_GATES';
export const READ_GATE = 'READ_GATE';
export const CREATE_GATE = 'CREATE_GATE';
export const UPDATE_GATE = 'UPDATE_GATE';
export const DELETE_GATE = 'DELETE_GATE';

export const READ_STRUCTURE_DECKS = 'READ_STRUCTURE_DECKS';
export const READ_STRUCTURE_DECK = 'READ_STRUCTURE_DECK';
export const CREATE_STRUCTURE_DECK = 'CREATE_STRUCTURE_DECK';
export const UPDATE_STRUCTURE_DECK = 'UPDATE_STRUCTURE_DECK';
export const DELETE_STRUCTURE_DECK = 'DELETE_STRUCTURE_DECK';

export const READ_DECKS = 'READ_DECKS';
export const READ_DECK = 'READ_DECK';
export const CREATE_DECK = 'CREATE_DECK';
export const UPDATE_DECK = 'UPDATE_DECK';
export const DELETE_DECK = 'DELETE_DECK';

export const CORE_INFO = 'CORE_INFO';
export const CONFIG_SHOW = 'CONFIG_SHOW';
export const CONFIG_SET_GAME_ROOT = 'CONFIG_SET_GAME_ROOT';
export const CONFIG_SET_SOURCE_ROOT = 'CONFIG_SET_SOURCE_ROOT';
export const WORKSPACE_INIT = 'WORKSPACE_INIT';
export const WORKSPACE_INSPECT = 'WORKSPACE_INSPECT';
export const CAMPAIGN_VALIDATE = 'CAMPAIGN_VALIDATE';
export const CAMPAIGN_DEPLOY = 'CAMPAIGN_DEPLOY';
export const RUNTIME_STATUS = 'RUNTIME_STATUS';
export const RUNTIME_FETCH = 'RUNTIME_FETCH';
export const DEPLOYMENT_LIST = 'DEPLOYMENT_LIST';
export const DEPLOYMENT_INSPECT = 'DEPLOYMENT_INSPECT';
export const DEPLOYMENT_LAUNCH = 'DEPLOYMENT_LAUNCH';
